# vim: set ft=dosini
---
version: "3"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: le
    ports:
      - 443:443
      - 80:80
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart: always

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=collinsbiegon9@gmail.com
      - URL=cyphercore.dev
      - ONLY_SUBDOMAINS=false
      - DHLEVEL=4096
      - TZ=Europe/London
      - VALIDATION=http