# vim: set ft=dosini
---
version: "3"
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: le
    ports:
      - 443:443
      - 80:80
    volumes:
      - /opt/appdata/letsencrypt:/config
    restart: always
    depends_on: 
      - cyphercore 
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - EMAIL=collinsbiegon9@gmail.com
      - URL=cyphercore.dev
      - ONLY_SUBDOMAINS=false
      - DHLEVEL=4096
      - TZ=Europe/London
      - VALIDATION=http
  cyphercore:
    image: grandmullah/cypherportfolio
    container_name: cyphercore
    ports: 
      - 3000:3000
    restart: always
